try ::error

diff --git a/.github/workflows/abi-diff.yml b/.github/workflows/abi-diff.yml
--- a/.github/workflows/abi-diff.yml
+++ b/.github/workflows/abi-diff.yml
@@ -155,7 +155,7 @@ jobs:
             if [[ $versions_eq -ne 0 ]]; then
               # versions not equal
           
-              echo "Files did not change but ABI version was changed" >&2
+              echo "::error::Files did not change but ABI version was changed"
               exit 1
             fi
           else
@@ -164,7 +164,7 @@ jobs:
             if [[ $versions_eq -eq 0 ]]; then
               # versions equal
           
-              echo "Files changed but ABI version was not changed" >&2
-              exit 2
+              echo "::error::Files changed but ABI version was not changed"
+              exit 1
             fi
           fi
